# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef7f25f4279d70edad3ae64be7c3581d26d5141940fb68c52c073c37ac8ac1c22da3a89b5d09a9f5588f184fe8fe96722ae54519aa35e2825e795b9356ae9a5c

test:
  secret_key_base: 0ab88dffe8f00275acd58d8e60ce6b9279abc67ccefa31f94a588dec1b69500dca4ff9e96ca4950132162d0376066cd9ce9f691b93a1246b3425f8aa99da3022

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
